# Generated by Django 3.2.23 on 2023-12-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorymap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='article_images/'),
        ),
    ]
