# Generated by Django 3.2.23 on 2023-12-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorymap', '0002_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
    ]
