# Generated by Django 3.2.25 on 2024-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorymap', '0004_auto_20240511_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('gif', 'GIF'), ('video', 'Video'), ('audio', 'Audio')], max_length=10),
        ),
    ]
