# Generated by Django 3.2.25 on 2024-05-15 03:55

from django.db import migrations, models
import memorymap.models


class Migration(migrations.Migration):

    dependencies = [
        ('memorymap', '0005_alter_media_media_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=memorymap.models.ThumbnailPath()),
        ),
    ]
