# Generated by Django 3.2.25 on 2024-05-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorymap', '0007_postaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
