# Generated by Django 3.2.25 on 2024-06-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorymap', '0008_delete_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
