# Generated by Django 3.2.25 on 2024-06-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorymap', '0010_auto_20240611_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
